### ISSUE TITLE
Compiler error with GCC 9.2.1: no matching function for call to ‘moodycamel::BlockingConcurrentQueue<T, Traits>::create<moodycamel::BlockingConcurrentQueue<T, Traits>::LightweightSemaphore>(int, int)’

### ISSUE THREAD

**Issue by philipp-paetzold** [cameron314/concurrentqueue#240]
When I compile with GCC 9.2.1 under CentOS Linux 8 (4.18.0-193.14.2.el8_2.x86_64) I get the following compiler errors with v1.02 of BlockingConcurrentQueue:

```
no matching function for call to ‘moodycamel::BlockingConcurrentQueue<T, Traits>::create<moodycamel::BlockingConcurrentQueue<T, Traits>::LightweightSemaphore>(int, int)’

   candidate: ‘template<class T, class Traits> template<class U, class A1, class A2> static U* moodycamel::BlockingConcurrentQueue<T, Traits>::create(A1&&, A2&&)’
   template argument deduction/substitution failed:
mismatched types ‘A1’ and ‘int’
```

**Comment by cameron314** [comment]
Looks like a duplicate of #218 (fixed). I'll create a new release (the master is stable anyway).

**Comment by cameron314** [comment]
https://github.com/cameron314/concurrentqueue/releases/tag/v1.0.3
