### ISSUE TITLE
A fully-working Threadpool task queue sample code

### ISSUE THREAD

**Issue by cayolblake** [cameron314/concurrentqueue#176]
Hello,

Is it possible to have a fully-working code that utilizes concurrentqueue?

I’ve examined the ones in https://github.com/cameron314/concurrentqueue/blob/master/samples.md and they’re either representing pseudo code or ones that are complex to understand for a beginner.

What I need is a fully-working example for Threadpool task queuing that have for example 3 worker threads and any random number of threads that posts tasks to these threads, and more importantly, an example that successfully compiles :) through g++ or clang.

Cheers!

**Comment by cameron314** [comment]
As far as I know all the samples are compilable code (though they are not full programs).

Here's how you might create a simple threadpool:

```
class ThreadPool {
public:
	explicit ThreadPool(size_t numWorkers) {
		workers.reserve(numWorkers);
		for (size_t i = 0; i != numWorkers; ++i)
			workers.push_back(std::thread(&pump, this));
	}

	~ThreadPool() {
		for (size_t i = 0; i != workers.size(); ++i)
			tasks.enqueue(Task(true));  // stop task
		for (auto& worker : workers)
			worker.join();
	}

	template<typename F>
	std::future<void> run(F const& f) {
		Task task;
		task.function = [=] { f(); };
		std::future<void> future = task.promise.get_future();
		tasks.enqueue(std::move(task));
		return std::move(future);
	}

	ThreadPool(ThreadPool const&) = delete;
	ThreadPool& operator=(ThreadPool const&) = delete;

private:
	static void pump(ThreadPool* pool) {
		Task task;
		moodycamel::ConsumerToken tok(pool->tasks);
		while (true) {
			pool->tasks.wait_dequeue(tok, task);
			if (task.stop)
				break;
			task.function();
			task.promise.set_value();
		}
	}

private:
	struct Task {
		explicit Task(bool stop = false) : stop(stop) { }
		Task(Task&& x) noexcept :
			function(std::move(x.function)),
			promise(std::move(x.promise)),
			stop(x.stop) { }
		Task& operator=(Task&& x) noexcept {
			std::swap(stop, x.stop);
			std::swap(function, x.function);
			std::swap(promise, x.promise);
			return *this;
		}

		std::function<void()> function;
		std::promise<void> promise;
		bool stop;
	};
private:
	std::vector<std::thread> workers;
	moodycamel::BlockingConcurrentQueue<Task> tasks;
};
```

**Comment by cameron314** [comment]
Usage:

```
ThreadPool tp(3);

// On any thread
auto future = tp.run([] { ... });
future.wait();  // if desired
```

**Comment by cayolblake** [comment]
Thanks. I expected a much simpler implementation but I’ll go through this and try to grasp it in the next few hours.

Almost all of the samples doesn’t compile on Mac OS X, I’ll open a different issue for that with the detailed output.

Is there any Slack channel you hang around?

**Comment by cayolblake** [comment]
That failed with the following, on Ubuntu 16.04.6 LTS 64bit running GCC 5.4.0 20160609.

```
ConcurrentQueueThreadPoolSample.cpp:72:45: error: wrong number of template arguments (1, should be 2)
     moodycamel::BlockingConcurrentQueue<Task> tasks;
                                             ^
In file included from ConcurrentQueueThreadPoolSample.cpp:5:0:
../concurrentqueue/concurrentqueue.h:367:45: note: provided for ‘template<class T, class Traits> class moodycamel::BlockingConcurrentQueue’
 template<typename T, typename Traits> class BlockingConcurrentQueue;
                                             ^
ConcurrentQueueThreadPoolSample.cpp: In destructor ‘ThreadPool::~ThreadPool()’:
ConcurrentQueueThreadPoolSample.cpp:20:19: error: request for member ‘enqueue’ in ‘((ThreadPool*)this)->ThreadPool::tasks’, which is of non-class type ‘int’
             tasks.enqueue(Task(true));  // stop task
                   ^
ConcurrentQueueThreadPoolSample.cpp: In member function ‘std::future<void> ThreadPool::run(const F&)’:
ConcurrentQueueThreadPoolSample.cpp:30:15: error: request for member ‘enqueue’ in ‘((ThreadPool*)this)->ThreadPool::tasks’, which is of non-class type ‘int’
         tasks.enqueue(std::move(task));
               ^
ConcurrentQueueThreadPoolSample.cpp: In static member function ‘static void ThreadPool::pump(ThreadPool*)’:
ConcurrentQueueThreadPoolSample.cpp:40:50: error: no matching function for call to ‘moodycamel::ConsumerToken::ConsumerToken(int&)’
         moodycamel::ConsumerToken tok(pool->tasks);
                                                  ^
In file included from ConcurrentQueueThreadPoolSample.cpp:5:0:
../concurrentqueue/concurrentqueue.h:653:2: note: candidate: moodycamel::ConsumerToken::ConsumerToken(moodycamel::ConsumerToken&&)
  ConsumerToken(ConsumerToken&& other) MOODYCAMEL_NOEXCEPT
  ^
../concurrentqueue/concurrentqueue.h:653:2: note:   no known conversion for argument 1 from ‘int’ to ‘moodycamel::ConsumerToken&&’
../concurrentqueue/concurrentqueue.h:651:11: note: candidate: template<class T, class Traits> moodycamel::ConsumerToken::ConsumerToken(moodycamel::BlockingConcurrentQueue<T, Traits>&)
  explicit ConsumerToken(BlockingConcurrentQueue<T, Traits>& q);
           ^
../concurrentqueue/concurrentqueue.h:651:11: note:   template argument deduction/substitution failed:
ConcurrentQueueThreadPoolSample.cpp:40:50: note:   mismatched types ‘moodycamel::BlockingConcurrentQueue<T, Traits>’ and ‘int’
         moodycamel::ConsumerToken tok(pool->tasks);
                                                  ^
In file included from ConcurrentQueueThreadPoolSample.cpp:5:0:
../concurrentqueue/concurrentqueue.h:648:11: note: candidate: template<class T, class Traits> moodycamel::ConsumerToken::ConsumerToken(moodycamel::ConcurrentQueue<T, Traits>&)
  explicit ConsumerToken(ConcurrentQueue<T, Traits>& q);
           ^
../concurrentqueue/concurrentqueue.h:648:11: note:   template argument deduction/substitution failed:
ConcurrentQueueThreadPoolSample.cpp:40:50: note:   mismatched types ‘moodycamel::ConcurrentQueue<T, Traits>’ and ‘int’
         moodycamel::ConsumerToken tok(pool->tasks);
                                                  ^
ConcurrentQueueThreadPoolSample.cpp:42:25: error: request for member ‘wait_dequeue’ in ‘pool->ThreadPool::tasks’, which is of non-class type ‘int’
             pool->tasks.wait_dequeue(tok, task);
                         ^
```


And that's the full code.


```
#include <thread>
#include <future>

#include "../concurrentqueue/concurrentqueue.h"

using namespace std;
using namespace moodycamel;

class ThreadPool {
   public:
    explicit ThreadPool(size_t numWorkers) {
        workers.reserve(numWorkers);
        for (size_t i = 0; i != numWorkers; ++i)
            workers.push_back(std::thread(&pump, this));
    }

    ~ThreadPool() {
        for (size_t i = 0; i != workers.size(); ++i)
            tasks.enqueue(Task(true));  // stop task
        for (auto& worker : workers)
            worker.join();
    }

    template <typename F>
    std::future<void> run(F const& f) {
        Task task;
        task.function = [=] { f(); };
        std::future<void> future = task.promise.get_future();
        tasks.enqueue(std::move(task));
        return std::move(future);
    }

    ThreadPool(ThreadPool const&) = delete;
    ThreadPool& operator=(ThreadPool const&) = delete;

   private:
    static void pump(ThreadPool* pool) {
        Task task;
        moodycamel::ConsumerToken tok(pool->tasks);
        while (true) {
            pool->tasks.wait_dequeue(tok, task);
            if (task.stop)
                break;
            task.function();
            task.promise.set_value();
        }
    }

   private:
    struct Task {
        explicit Task(bool stop = false)
            : stop(stop) {}
        Task(Task&& x) noexcept
            : function(std::move(x.function)),
              promise(std::move(x.promise)),
              stop(x.stop) {}
        Task& operator=(Task&& x) noexcept {
            std::swap(stop, x.stop);
            std::swap(function, x.function);
            std::swap(promise, x.promise);
            return *this;
        }

        std::function<void()> function;
        std::promise<void> promise;
        bool stop;
    };

   private:
    std::vector<std::thread> workers;
    moodycamel::BlockingConcurrentQueue<Task> tasks;
};
```

**Comment by cameron314** [comment]
I could try joining a Slack channel if you have one in mind. I'm not in any right now (apart from work).

**Comment by cameron314** [comment]
My sample code compiles in VS2019 and g++ 5.3.1.
You need to include `blockingconcurrentqueue.h` instead of `concurrentqueue.h`.

**Comment by cayolblake** [comment]
> I could try joining a Slack channel if you have one in mind. I'm not in any right now (apart from work).

I'd suggest naturally https://cpplang.slack.com

I searched for you there before posting an issue here ;)

**Comment by cayolblake** [comment]
> My sample code compiles in VS2019 and g++ 5.3.1.
> You need to include `blockingconcurrentqueue.h` instead of `concurrentqueue.h`.

Yes, replacing `concurrentqueue.h` with `blockingconcurrentqueue.h` does the job.

**Comment by cayolblake** [comment]
Now attempting to just use it with `ThreadPool tp(3);` in my `main()` I get.

```
/tmp/cclgFmbw.o: In function `moodycamel::details::Semaphore::Semaphore(int)':
BlockingQueueThreadPoolSample.cpp:(.text._ZN10moodycamel7details9SemaphoreC2Ei[_ZN10moodycamel7details9SemaphoreC5Ei]+0x3e): undefined reference to `sem_init'
/tmp/cclgFmbw.o: In function `moodycamel::details::Semaphore::~Semaphore()':
BlockingQueueThreadPoolSample.cpp:(.text._ZN10moodycamel7details9SemaphoreD2Ev[_ZN10moodycamel7details9SemaphoreD5Ev]+0x14): undefined reference to `sem_destroy'
/tmp/cclgFmbw.o: In function `moodycamel::details::Semaphore::wait()':
BlockingQueueThreadPoolSample.cpp:(.text._ZN10moodycamel7details9Semaphore4waitEv[_ZN10moodycamel7details9Semaphore4waitEv]+0x14): undefined reference to `sem_wait'
/tmp/cclgFmbw.o: In function `moodycamel::details::Semaphore::try_wait()':
BlockingQueueThreadPoolSample.cpp:(.text._ZN10moodycamel7details9Semaphore8try_waitEv[_ZN10moodycamel7details9Semaphore8try_waitEv]+0x14): undefined reference to `sem_trywait'
/tmp/cclgFmbw.o: In function `moodycamel::details::Semaphore::timed_wait(unsigned long)':
BlockingQueueThreadPoolSample.cpp:(.text._ZN10moodycamel7details9Semaphore10timed_waitEm[_ZN10moodycamel7details9Semaphore10timed_waitEm]+0xdb): undefined reference to `sem_timedwait'
/tmp/cclgFmbw.o: In function `moodycamel::details::Semaphore::signal(int)':
BlockingQueueThreadPoolSample.cpp:(.text._ZN10moodycamel7details9Semaphore6signalEi[_ZN10moodycamel7details9Semaphore6signalEi]+0x29): undefined reference to `sem_post'
/tmp/cclgFmbw.o: In function `std::thread::thread<void (*)(ThreadPool*), ThreadPool*>(void (*&&)(ThreadPool*), ThreadPool*&&)':
BlockingQueueThreadPoolSample.cpp:(.text._ZNSt6threadC2IPFvP10ThreadPoolEJS2_EEEOT_DpOT0_[_ZNSt6threadC5IPFvP10ThreadPoolEJS2_EEEOT_DpOT0_]+0x93): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
```

**Comment by cameron314** [comment]
You need to compile with `-pthread`

**Comment by cameron314** [comment]
I'm on Cpplang now (passively) if anyone @ mentions me.

**Comment by cameron314** [comment]
Closing for now. Reopen as needed.
