### ISSUE TITLE
Failed compile with gcc 6.4

### ISSUE THREAD

**Issue by pengweichu** [cameron314/concurrentqueue#141]
I've tried compile it with my project on CentOS 7 + GCC 6.4 in CMAKE, I got below error:

> 
> /include/concurrentqueue/concurrentqueue.h:2460:41: error: call of overloaded ‘operator new(sizetype, std::nullptr_t)’ is ambiguous
>      if (!MOODYCAMEL_NOEXCEPT_CTOR(T, U, new (nullptr) T(std::forward<U>(element)))) {
>                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /include/concurrentqueue/concurrentqueue.h:188:66: note: in definition of macro ‘MOODYCAMEL_NOEXCEPT_CTOR’
>  #define MOODYCAMEL_NOEXCEPT_CTOR(type, valueType, expr) noexcept(expr)
>

**Comment by cameron314** [comment]
Never saw this before. What was the solution?
