### ISSUE TITLE
won't compile on FreeBSD CLANG version 3.4.1

### ISSUE THREAD

**Issue by vikingsloth** [cameron314/concurrentqueue#9]
<pre>
c++ -g -O2 -D_BSD_SOURCE -DLIBNET_BSDISH_OS -DLIBNET_BSD_BYTE_SWAP -DHAVE_SOCKADDR_SA_LEN -I.. -I/usr/local/include -std=c++11 -c log_queue.cpp
In file included from log_queue.cpp:8:
../utils/concurrentqueue.hpp:1622:65: error: expected expression
  ...auto newBlock = this->parent->requisition_block<allocMode>();
                                                                ^
../utils/concurrentqueue.hpp:1828:65: error: expected expression
  ...auto newBlock = this->parent->requisition_block<allocMode>();
                                                                ^
../utils/concurrentqueue.hpp:2214:64: error: expected expression
  ...auto newBlock = this->parent->requisition_block<allocMode>();
                                                                ^
../utils/concurrentqueue.hpp:2363:159: error: expected expression
  ...|| (newBlock = this->parent->requisition_block<allocMode>()) == nullptr) {
                                                               ^
</pre>

The arrow is pointing to the last brace in "<allocMode>();".

**Comment by cameron314** [comment]
Thanks for opening an issue! Unfortunately, I don't have the software installed to reproduce this. If you add `template ConcurrentQueue::` before the method calls, does it resolve the issue?

Example:

    auto newBlock = this->parent->template ConcurrentQueue::requisition_block<allocMode>();

**Comment by vikingsloth** [comment]
Thanks. I got it to compile like this:
<pre>
auto newBlock = this->parent->template requisition_block<allocMode>();
</pre>

**Comment by cameron314** [comment]
Hmm, there should be template parameter of `<allocMode>` before the `()`. The line you've posted shouldn't compile(!).

Also, does the fully-qualified variant that I posted (`template ConcurrentQueue::requisition_block<allocMode>()`) compile as well? Because that one's to be preferred in order to [avoid clashes with global symbols named `requisition_block` with certain compilers](http://stackoverflow.com/questions/27930448/why-does-this-dependent-name-lookup-find-a-global-identifier-instead-of-the-meth).

**Comment by cameron314** [comment]
Oops, sorry for the issue close/open spam, I hit the wrong button twice ><

**Comment by vikingsloth** [comment]
It was a typo. Here's cut and pasted from the modified file
<pre>
 auto newBlock = this->parent->template requisition_block<allocMode>();
</pre>

**Comment by vikingsloth** [comment]
Oh, it's the html stripping code in github removing it

**Comment by cameron314** [comment]
Oh! Weird, usually it leaves code blocks alone. OK, one mystery solved :-)
Does the fully-qualified version work for you too?

**Comment by vikingsloth** [comment]
```
auto newBlock = this->parent->template requisition_block<allocMode>();
```

**Comment by vikingsloth** [comment]
Fully qualified didn't work.

```
../utils/concurrentqueue.hpp:1622:60: error: expected ';' at end of declaration
  ...auto newBlock = this->parent->template ConcurrentQueue::requisition_bloc...
                                                           ^
                                                           ;
../utils/concurrentqueue.hpp:1622:60: error: no template named
      'requisition_block' in the global namespace; did you mean simply
      'requisition_block'?
  ...newBlock = this->parent->template ConcurrentQueue::requisition_block<all...
                                                      ^~~~~~~~~~~~~~~~~~~
                                                      requisition_block
../utils/concurrentqueue.hpp:2777:9: note: 'requisition_block' declared here
        Block* requisition_block()
```

**Comment by cameron314** [comment]
Oops, I must be getting tired. I put the `template` in the wrong spot, sorry. This should work:

    auto newBlock = this->parent->ConcurrentQueue::template requisition_block<allocMode>();

**Comment by vikingsloth** [comment]
Compiles cleanly with that as well

**Comment by cameron314** [comment]
Perfect, thanks a lot for your help. I'll commit a fix.
