### ISSUE TITLE
Relacy tests fail to compile on Linux/g++5.3.1

### ISSUE THREAD

**Issue by alcontre** [cameron314/concurrentqueue#102]
Hi,
I'm trying to build and run the relacy tests under CentOS (using g++ version 5.3.1), and the build is bombing out with the following:

[user@localhost concurrentqueue-master]$ cd tests/relacy/
[user@localhost relacy]$ make
g++ -std=c++11 -fpermissive -pthread -lrt -O3 -g freelist.cpp -o freelist
In file included from freelist.cpp:3:0:
relacy/relacy/relacy_std.hpp:22:15: error: ‘memory_order’ is already declared in this scope
     using rl::memory_order;
               ^
relacy/relacy/relacy_std.hpp:30:15: error: ‘atomic’ is already declared in this scope
     using rl::atomic;
               ^
make: *** [freelist] Error 1
[user@localhost relacy]$ 

Any thoughts? Happy holidays!

**Comment by cameron314** [comment]
Hmm, I'll have a look at this soon. Thanks for raising an issue!

**Comment by cameron314** [comment]
It looks like Relacy isn't compatible with GCC 5.3. The version that's in the repository is rather old at this point. I'll have to try updating it.

**Comment by cameron314** [comment]
Even the latest Relacy still has this incompatibility. It arises because later versions of GCC define `std::atomic` and `std::memory_order` when including `<memory>`, which breaks Relacy (since it expressly does not include the `<atomic>` header in order to furnish its own replacements).

I've updated Relacy and patched it to fix this (see relacy/relacy_std.hpp). The tests still pass.
I'm not going to submit a pull request upstream since my fix is only partial (enough to get just my tests to compile).
